### ISSUE TITLE
Bug: RegisterPoints

### ISSUE THREAD

**Issue by nancikennedy** [kemayo/wow-handynotes-stygia#1]
On Retail, with latest (alpha) version installed, this happens when logging in/reloading:

Message: Interface/AddOns/HandyNotes_Stygia/stygia.lua:13: attempt to call field 'RegisterPoints' (a nil value)
Time: Sat Nov 19 19:43:20 2022
Count: 1
Stack: Interface/AddOns/HandyNotes_Stygia/stygia.lua:13: attempt to call field 'RegisterPoints' (a nil value)
[string "@Interface/AddOns/HandyNotes_Stygia/stygia.lua"]:13: in main chunk

Locals: myname = "HandyNotes_Stygia"
ns = <table> {
 hiddenConfig = <table> {
 }
}
(*temporary) = nil
(*temporary) = 1543
(*temporary) = <table> {
 17745294 = <table> {
 }
 23473457 = <table> {
 }
 19153426 = <table> {
 }
 45036659 = <table> {
 }
 19236727 = <table> {
 }
 26346862 = <table> {
 }
 33044229 = <table> {
 }
 46258128 = <table> {
 }
 55247788 = <table> {
 }
 51567853 = <table> {
 }
 53496632 = <table> {
 }
 48148380 = <table> {
 }
 26352906 = <table> {
 }
 15915168 = <table> {
 }
 54207930 = <table> {
 }
 29321826 = <table> {
 }
 17584995 = <table> {
 }
 57178508 = <table> {
 }
 19403788 = <table> {
 }
 19096746 = <table> {
 }
 67045548 = <table> {
 }
 29311823 = <table> {
 }
 23004450 = <table> {
 }
 35446747 = <table> {
 }
 61076916 = <table> {
 }
 60866755 = <table> {
 }
 58917834 = <table> {
 }
 23004470 = <table> {
 }
 59007840 = <table> {
 }
 27916014 = <table> {
 }
 41194945 = <table> {
 }
 24134281 = <table> {
 }
 52157841 = <table> {
 }
 56766011 = <table> {
 }
 19633539 = <table> {
 }
 38701943 = <table> {
 }
 56677092 = <table> {
 }
 55467721 = <table> {
 }
 19243429 = <table> {
 }
 55067753 = <table> {
 }
 40004900 = <table> {
 }
 23307387 = <table> {
 }
 24526844 = <table> {
 }
 54618000 = <table> {
 }
 23297380 = <table> {
 }
 54526717 = <table> {
 }
 54515845 = <table> {
 }
 54368484 = <table> {
 }
 54278488 = <table> {
 }
 20653858 = <table> {
 }
 51478384 = <table> {
 }
 34007037 = <table> {
 }
 32396744 = <table> {
 }
 22952220 = <table> {
 }
 36254216 = <table> {
 }
 53288031 = <table> {
 }
 47166240 = <table> {
 }
 53266871 = <table> {
 }
 53157841 = <table> {
 }
 24246534 = <table> {
 }
 25796891 = <table> {
 }
 52976863 = <table> {
 }
 29676552 = <table> {
 }
 21326569 = <table> {
 }
 18914631 = <table> {
 }
 52187614 = <table> {
 }
 52038191 = <table> {
 }
 26764483 = <table> {
 }
 53985866 = <table> {
 }
 51437820 = <table> {
 }
 21737190 = <table> {
 }
 16015170 = <table> {
 }
 50037306 = <table> {
 }
 50007460 = <table> {
 }
 48397060 = <table> {
 }
 16915500 = <table> {
 }
 47136246 = <table> {
 }
 44356704 = <table> {
 }
 20623857 = <table> {
 }
 41314786 = <table> {
 }
 28694933 = <table> {
 }
 19353800 = <table> {
 }
 23523465 = <table> {
 }
 43806884 = <table> {
 }
 33617490 = <table> {
 }
 57465194 = <table> {
 }
 40124908 = <table> {
 }
 23167000 = <table> {
 }
 25236567 = <table> {
 }
 51867087 = <table> {
 }
 18295453 = <table> {
 }
 58095186 = <table> {
 }
 24344688 = <table> {
 }
 22495479 = <table> {
 }
 53917700 = <table> {
 }
 30222837 = <table> {
 }
 33174245 = <table> {
 }
 33156481 = <table> {
 }
 33102066 = <table> {
 }
 32586494 = <table> {
 }
 27427225 = <table> {
 }
 22946816 = <table> {
 }
 33986205 = <table> {
 }
 30216580 = <table> {
 }
 24603005 = <table> {
 }
 52957023 = <table> {
 }
 29646541 = <table> {
 }
 34027035 = <table> {
 }
 21656684 = <table> {
 }
 28384546 = <table> {
 }
 28006050 = <table> {
 }
 28384548 = <table> {
 }
 23716550 = <table> {
 }
 26852750 = <table> {
 }
 37544334 = <table> {
 }
 26153093 = <table> {
 }
 25633108 = <table> {
 }
 24191661 = <table> {
 }
 27362594 = <table> {
 }
 37804500 = <table> {
 }
 16875504 = <table> {
 }
 23007168 = <table> {
 }
}
(*temporary) = <table> {
 requires_item = 184870
 inbag = 185474
 group = "Stygia Nexus"
 label = "Stygia Nexus"
 quest = 63684
 atlas = "vehicle-templeofkotmogu-greenball"
}
(*temporary) = "attempt to call field 'RegisterPoints' (a nil value)"

**Comment by kemayo** [comment]
There was a problem with the build that I've fixed and I'm getting a new release out now. Thanks for letting me know about it!
