### ISSUE TITLE
Bug: Stygia.lua null

### ISSUE THREAD

**Issue by nancikennedy** [kemayo/wow-handynotes-stygia#3]
On Retail, with the latest (alpha) version installed:

Message: Interface/AddOns/HandyNotes_Stygia/stygia.lua:1 (null)
Time: Sat Nov 19 19:43:27 2022
Count: 1

**Comment by nancikennedy** [comment]
Also getting:

Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/HandyNotes_Stygia/stygia.lua:1 (null)
Time: Sat Nov 19 19:43:27 2022
Count: 1

**Comment by nancikennedy** [comment]
These happen when logging in/reloading

**Comment by Gnomexpress** [comment]
Folder Handler non available in your last build

**Comment by kemayo** [comment]
Should all be fixed in the new release
